// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpSVmMWgp8tv0WbAk38tDpyV25Aae2mWE',
    appId: '1:1087336647033:web:294f272634b200dc4bc7a8',
    messagingSenderId: '1087336647033',
    projectId: 'skills-audit-system-a5ba3',
    authDomain: 'skills-audit-system-a5ba3.firebaseapp.com',
    storageBucket: 'skills-audit-system-a5ba3.firebasestorage.app',
    measurementId: 'G-PTF971RNQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkFLn1IBOWExS2dsBeqK6zCOgTsqwyDgQ',
    appId: '1:1087336647033:android:a0eb0e23af7dd9684bc7a8',
    messagingSenderId: '1087336647033',
    projectId: 'skills-audit-system-a5ba3',
    storageBucket: 'skills-audit-system-a5ba3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNzPwr6pHNEO26bEnsK9jfRbIuWjZbwAQ',
    appId: '1:1087336647033:ios:caf4a264923d3d2d4bc7a8',
    messagingSenderId: '1087336647033',
    projectId: 'skills-audit-system-a5ba3',
    storageBucket: 'skills-audit-system-a5ba3.firebasestorage.app',
    iosBundleId: 'com.example.skillAduitSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNzPwr6pHNEO26bEnsK9jfRbIuWjZbwAQ',
    appId: '1:1087336647033:ios:caf4a264923d3d2d4bc7a8',
    messagingSenderId: '1087336647033',
    projectId: 'skills-audit-system-a5ba3',
    storageBucket: 'skills-audit-system-a5ba3.firebasestorage.app',
    iosBundleId: 'com.example.skillAduitSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpSVmMWgp8tv0WbAk38tDpyV25Aae2mWE',
    appId: '1:1087336647033:web:be7bf784c53812f94bc7a8',
    messagingSenderId: '1087336647033',
    projectId: 'skills-audit-system-a5ba3',
    authDomain: 'skills-audit-system-a5ba3.firebaseapp.com',
    storageBucket: 'skills-audit-system-a5ba3.firebasestorage.app',
    measurementId: 'G-CER2E6KZXE',
  );
}
